services:
  postgres:
    image: postgres:latest
    ports:
      - "5556:5432"
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: database
    volumes:
      - pgdata:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:latest
    environment:
      RABBITMQ_DEFAULT_PASS: secret
      RABBITMQ_DEFAULT_USER: myuser
    ports:
      - "5672:5672"

volumes:
  pgdata: